name: Publish Tag Image

on:
  push:
    branches: ["main"]

jobs:
  hello:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # required for git push from actions
      packages: write  # required for docker push

    steps:
    - uses: actions/checkout@v4

    - run: |
        find tag-files/ -type f -exec \
          sed -i 's/\btag 1\b/tag 2/g' {} \;

    - name: Push files with replaced content
      # checkout@v2 and up will automatically set up the GITHUB_TOKEN for
      # pushing, and therefore will not create a new recursive workflow run.
      run: |
        git config user.name "GitHub Actions"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add tag-files/ && git commit -m "Replace tags" && git push

    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v6
      with:
        context: .
        tags: |
          ghcr.io/${{ github.repository }}
        push: true
